### ISSUE TITLE
Wikiseite Fahrzeugverwaltung

### ISSUE THREAD

**Issue by MultiKnacker** [MultiKnacker/Projekt-WIN#18]

**Comment by Kaya42** [comment]
![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/dd17d5f8-1626-4110-b3ee-3eb558605219)

![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/17d605b8-153f-4444-96e5-b108a0497b76)

![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/83f478ea-5289-4e16-bfb7-1d560c2687e4)

![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/3aa50a87-3f96-4b94-b9c4-739c91d7bf3e)

![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/753ef72a-488d-44a5-aaf3-416322d49bdf)

![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/5b0c452b-6b61-4828-87c8-80814b7e4e8a)

![image](https://github.com/MultiKnacker/Projekt-WIN/assets/114980333/1ae6be3a-6964-42e7-b382-6e7fee45d259)

**Comment by MultiKnacker** [comment]
Sah fertig aus, wird geschlossen.
