### ISSUE TITLE
Suchleiste setzt sich nach dem suchen bei Fahrzeugverwaltung zurück

### ISSUE THREAD

**Issue by Nico-dhls** [MultiKnacker/Projekt-WIN#25]
**Describe the bug**
Wenn man auf der Seite Fahrzeugverwaltung etwas sucht, setzt sich die Suchleiste jedes mal zurück, bei den anderen beiden Seiten funktioniert es

**To Reproduce**
1. Gehe zu Fahrzeugverwaltung
2. Gebe etwas in die Suchleiste ein
3. Drück Enter
4. Suchleiste zurückgesetzt

**Expected behavior**
Die Suchleiste sollte ihren Input behalten

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by MultiKnacker** [comment]
Gefixt und suchleisten Feature hinzugefügt
