### ISSUE TITLE
FahrzeugView

### ISSUE THREAD

**Issue by FabianShalk** [MultiKnacker/Projekt-WIN#5]
Erstellen der FahrzeuView nach Vorlage aus dem Figma Mockup.

In dem Projekt findet sich bereits ein Routing zu einem Blueprint und HTML Datei. 

Blueprint > vehicle.py
Template > vehicleview.html

**Comment by MultiKnacker** [comment]
Button funktionieren nicht
Anzeigen von der Mietstation, in welcher das Fahrzeug steht muss noch implementiert werden

**Comment by MultiKnacker** [comment]
Seite vorerst fertig und Issue abgeschlossen
