### ISSUE TITLE
PersonalverwaltungsView

### ISSUE THREAD

**Issue by FabianShalk** [MultiKnacker/Projekt-WIN#6]
Erstellen der PersonalverwaltungView nach Vorlage aus dem Figma Mockup.

In dem Projekt findet sich bereits ein Routing zu einem Blueprint und HTML Datei. 

Blueprint > management.py
Template > managementview.html

**Comment by MultiKnacker** [comment]
Management view implementiert
suchleiste funktioniert
Todo:
Editieren von Mitarbeitern

**Comment by MultiKnacker** [comment]
Fertig soweit. Evtl werden weitere Funktionen implementiert oder das Design überarbeitet

**Comment by MultiKnacker** [comment]
Abfangen von falschen eingaben muss noch implementiert werden

**Comment by MultiKnacker** [comment]
Falsche eingaben werden abgefangen bei Straßennamen und PLZ. Leere Felder führen zu Fehlermeldung und hindern User am Speichern
