### ISSUE TITLE
PerformanceView

### ISSUE THREAD

**Issue by FabianShalk** [MultiKnacker/Projekt-WIN#7]
Erstellen der PerformanceView nach Vorlage aus dem Figma Mockup.

In dem Projekt findet sich bereits ein Routing zu einem Blueprint und HTML Datei. 

Blueprint > performance.py
Template > performance.html

Aufmachen der Seite soll ein System interne Preview zeigen. Sosnt findet sich auf der Seite ein Butoon zm downloaden einem PDF. 
Klicken öffnet ein Browser internen PDFReader von wo man dann den File speichern kann.

**Comment by MultiKnacker** [comment]
- Plotting (bokeh?)
